import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { NavLink } from '@/components/NavLink'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav>
          <Link href="/">VBS</Link>

          <ol>
            <NavLink route="about" />
            <NavLink route="experience" />
            <NavLink route="work" />
            <NavLink route="contact" />
          </ol>
        </nav>
      </header>
      <div className={styles.sideNav}>
        <ul>
          <li>
            <Link href="/">
              <Image
                src="/github.svg"
                alt="Github Logo"
                width={25}
                height={25}
                priority
              />
            </Link>
          </li>
          <li>
            <Link href="/">
              <Image
                src="/linkedin.svg"
                alt="Linkedin Logo"
                width={25}
                height={25}
                priority
              />
            </Link>
          </li>
          <li>
            <Link href="/">
              <Image
                src="/instagram.svg"
                alt="Instagram Logo"
                width={25}
                height={25}
                priority
              />
            </Link>
          </li>
          <li>
            <Link href="/">
              <Image
                src="/twitter.svg"
                alt="Twitter Logo"
                width={25}
                height={25}
                priority
              />
            </Link>
          </li>
          <li>
            <Link href="/">
              <Image
                src="/mail.svg"
                alt="Email Logo"
                width={25}
                height={25}
                priority
              />
            </Link>
          </li>
        </ul>
      </div>
      <main className={styles.main}>
        <section></section>
      </main>
    </>
  )
}
